### ISSUE TITLE
Blueprints - The mod crashes when you create a blueprints including a Mechanized Airlock

### ISSUE THREAD

**Issue by youralmight** [Pt-Djefferson/ONIMods#12]
Mod version: 2.4.9.7
Game version: U47-562984-S
Date: 2023-08-03
How to reproduce: Create a blueprint or snapshot with buildings included.
Expected: The blueprint is created.
What happened: The game crashed.
Log:
![image](https://github.com/Pt-Djefferson/ONIMods/assets/42952005/5c4e90f7-31bb-452e-9a91-9614cfd1b900)

I trialed many times to find only when a Mechanized Airlock is included does the mod crash.

**Comment by Pt-Djefferson** [comment]
Check Blueprints.dll version directly 
![image](https://github.com/Pt-Djefferson/ONIMods/assets/5026470/e86c3e03-9e73-4e15-b3af-0c8fe2405354)
Looks like your Blueprints.dll file is 2.4.9.6. I saw it with my own eyes when ingame mod verison was 2.4.9.7 but Blueprints.dll version was 2.4.9.6 (with Mechanized Airlock crash).

**Comment by youralmight** [comment]
True.

I checked my dll version which turned out to be 2.4.9.7.
It seems steam didn't update the mod automatically. The problem is solved after I subscribed "mod updater"

**Comment by youralmight** [comment]
True.

I checked my dll version which turned out to be 2.4.9.6.
It seems steam didn't update the mod automatically. The problem is solved after I subscribed "mod updater"
