### ISSUE TITLE
Tool filter: MISSING.STRINGS.UI.TOOLS

### ISSUE THREAD

**Issue by Knofbath** [Pt-Djefferson/ONIMods#14]
Looks like GASCONDUIT is now GASPIPES, and LIQUIDCONDUIT is now LIQUIDPIPES.

Are you maybe not passing the .NAME field? They all have .NAME and .TOOLTIP now.

#. STRINGS.UI.TOOLS.FILTERLAYERS.BACKWALL.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.BACKWALL.NAME"
msgid "Background Buildings"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.BUILDINGS.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.BUILDINGS.NAME"
msgid "Buildings"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.DIGPLACER.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.DIGPLACER.NAME"
msgid "Dig Orders"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.GASPIPES.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.GASPIPES.NAME"
msgid "Gas Pipes"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.LIQUIDPIPES.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.LIQUIDPIPES.NAME"
msgid "Liquid Pipes"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.LOGIC.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.LOGIC.NAME"
msgid "Automation"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.SOLIDCONDUITS.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.SOLIDCONDUITS.NAME"
msgid "Conveyor Rails"
msgstr ""

#. STRINGS.UI.TOOLS.FILTERLAYERS.WIRES.NAME
msgctxt "STRINGS.UI.TOOLS.FILTERLAYERS.WIRES.NAME"
msgid "Power Wires"
msgstr ""

**Comment by Pt-Djefferson** [comment]
thx
