### ISSUE TITLE
Missing License Specification

### ISSUE THREAD

**Issue by DDEle** [Pt-Djefferson/ONIMods#3]
> Currently No license is specified in Github's Project License option, nor is one listed in the project source (typically license.txt or license.md).
> 
> The problem with this is without it there's no way to determine if you can use BPNI in your projects. No license is not a presumption of Public Domain, and even if it was I don't expect that's what the author intended.
> 
> Please Spend 5min to add FOSS/OSS license details.
> 
> https://choosealicense.com/ goes through a step by step basis of picking a license to make it easier for use non lawyers to figure out what we want.

The above wording is copied from https://github.com/simonlourson/blueprintnotincluded/issues/6

**Comment by Pt-Djefferson** [comment]
The original project is licensed under a private license so I can't relicense mine. The author of the original project does not want to change anything, just allowed me to bring it to a working state.
