### ISSUE TITLE
Blueprints- Crashing Game on Fast Friends Update

### ISSUE THREAD

**Issue by ospar0829** [Pt-Djefferson/ONIMods#4]
MissingMethodException: void SpeedControlScreen.Pause(bool)

PlayerController.OnKeyDown (KButtonEvent e) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <3366109ff608488f8317d0b43357f1ba>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <3366109ff608488f8317d0b43357f1ba>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <3366109ff608488f8317d0b43357f1ba>:0)
KInputController.Dispatch () (at <3366109ff608488f8317d0b43357f1ba>:0)
KInputManager.Dispatch () (at <3366109ff608488f8317d0b43357f1ba>:0)
KInputManager.Update () (at <3366109ff608488f8317d0b43357f1ba>:0)
GameInputManager.Update () (at <3366109ff608488f8317d0b43357f1ba>:0)
Global.Update () (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)

Build: U42-509629-S

**Comment by ezonius** [comment]
@Pt-Djefferson Updating PLib seems to fix the problem

**Comment by ezonius** [comment]
#5 
Meanwhile people can install this locally. As far as I could test, everything works again. Only tested on Spaced Out!
[Blueprints.zip](https://github.com/Pt-Djefferson/ONIMods/files/8836007/Blueprints.zip)

**Comment by Pt-Djefferson** [comment]
PLib updated.
