### ISSUE TITLE
The mod does'nt wotk anymore.

### ISSUE THREAD

**Issue by turkishviking** [Pt-Djefferson/ONIMods#9]
Hi, the mod does'nt work anymore, it cause a game crash when pressing key to switch BP.
Here the log, bye:

MissingMethodException: void SpeedControlScreen.Pause(bool)

PlayerController.OnKeyDown (KButtonEvent e) (at <1c7e9ccb4aa844e2be4538990aabf98e>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
KInputController.Dispatch () (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
KInputManager.Dispatch () (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
KInputManager.Update () (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
GameInputManager.Update () (at <8c239b169b544cce8b8bc7ddd2d09e10>:0)
Global.Update () (at <1c7e9ccb4aa844e2be4538990aabf98e>:0)

Build: U42-514967-S

**Comment by songokussm** [comment]
This is the error i get:

IndexOutOfRangeException: Index was outside the bounds of the array.

Grid+ObjectLayerIndexer.get_Item (System.Int32 cell, System.Int32 layer) (at <cb20703507b14eea8088dbc44abf7f85>:0)
Blueprints.TileVisual.Clean () (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.TileVisual.UpdateGrid (System.Int32 cell) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.TileVisual..ctor (Blueprints.BuildingConfig buildingConfig, System.Int32 cell) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.BlueprintsState.VisualizeBlueprint (Vector2I topLeft, Blueprints.Blueprint blueprint) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.UseBlueprintTool.OnKeyDown (KButtonEvent buttonEvent) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
PlayerController.OnKeyDown (KButtonEvent e) (at <cb20703507b14eea8088dbc44abf7f85>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KInputHandler.HandleKeyDown (KButtonEvent e) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KInputHandler.HandleEvent (KInputEvent e) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KInputController.Dispatch () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KInputManager.Dispatch () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KInputManager.Update () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
GameInputManager.Update () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
Global.Update () (at <cb20703507b14eea8088dbc44abf7f85>:0)

Build: U43-526233-SD

**Comment by tangbenDY** [comment]
IndexOutOfRangeException: Index was outside the bounds of the array.

Grid+ObjectLayerIndexer.get_Item (System.Int32 cell, System.Int32 layer) (at <cb20703507b14eea8088dbc44abf7f85>:0)
Blueprints.TileVisual.Clean () (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.TileVisual.UpdateGrid (System.Int32 cell) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.TileVisual..ctor (Blueprints.BuildingConfig buildingConfig, System.Int32 cell) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.BlueprintsState.VisualizeBlueprint (Vector2I topLeft, Blueprints.Blueprint blueprint) (at <ce572e186dd540e083b08b5dbdb2f895>:0)
Blueprints.UseBlueprintTool.OnActivateTool () (at <ce572e186dd540e083b08b5dbdb2f895>:0)
InterfaceTool.ActivateTool () (at <cb20703507b14eea8088dbc44abf7f85>:0)
PlayerController.ActivateTool (InterfaceTool tool) (at <cb20703507b14eea8088dbc44abf7f85>:0)
ToolMenu.ChooseTool (ToolMenu+ToolInfo tool) (at <cb20703507b14eea8088dbc44abf7f85>:0)
ToolMenu.OpenOrCloseCollectionsInRow (System.Collections.Generic.IList`1[T] row, System.Boolean autoSelectTool) (at <cb20703507b14eea8088dbc44abf7f85>:0)
ToolMenu.<ChooseCollection>b__64_0 (System.Collections.Generic.List`1[T] row) (at <cb20703507b14eea8088dbc44abf7f85>:0)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <695d1cc93cca45069c528c15c9fdd749>:0)
ToolMenu.ChooseCollection (ToolMenu+ToolCollection collection, System.Boolean autoSelectTool) (at <cb20703507b14eea8088dbc44abf7f85>:0)
ToolMenu+<>c__DisplayClass60_0.<InstantiateCollectionsUI>b__0 () (at <cb20703507b14eea8088dbc44abf7f85>:0)
Util.Signal (System.Action action) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KToggle.Click () (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
KToggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <1b5c2ff4f53d4a48b7159ed84d905978>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <0b23117e1c7442f8b1842fe2f3bf6fcb>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <0b23117e1c7442f8b1842fe2f3bf6fcb>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U43-526233-S

**Comment by Pt-Djefferson** [comment]
mods updated

**Comment by songokussm** [comment]
Thank you!!
